### PR TITLE
SDC-5460_SDC-5461: Instance Scheduler Auto-Shutdown Deploy Lambda w/Terraform

### PR DESCRIPTION
**Pull request by JeffUssing**
## Pull Request Information
| Proposed Release Date  | Repository                                                    | Version/Tag                                                                         | Release Type  | Risk Type  | Expected Downtime  |
|------------------------|---------------------------------------------------------------|-------------------------------------------------------------------------------------|---------------|------------|--------------------|
| 2022-00-00             | [infrastructure](https://github.com/USDOT-SDC/infrastructure) | [0.3.0 vs 0.4.0](https://github.com/USDOT-SDC/infrastructure/compare/0.3.0...0.4.0) | Fast Track    | Low        | None               |

## Release
- https://github.com/USDOT-SDC/infrastructure/releases/tag/0.4.0

## Release Notes
- [Release Notes](https://github.com/USDOT-SDC/infrastructure/blob/0.4.0/RELEASE-NOTES.md)

## Summary
- Add global schedule to instance scheduler

## Work Items
- https://securedatacommons.atlassian.net/browse/SDC-5460
  - https://securedatacommons.atlassian.net/browse/SDC-5461

## Release Notifications
- None

## Cost Impacts
- System cost impacts

## User Guide Updates
- [RT Guide: Chapter 7, Workstation Scheduler](https://securedatacommons.atlassian.net/wiki/spaces/DESK/pages/2459566081)

## Process, Procedure and Work Instruction
- [Process: Development](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/1332379871)
  - [Procedure: Infrastructure](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2437218305)
    - [WI: Infrastructure, Infrastructure Deployment](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2501017629)

## Impacted System Components
- Instance Scheduler

## Data Load/Processing Impact
- None

## Release Type/Risk Level classification justification
- Release Type: Fast Track
- Risk Level: Low (0)

### Risk Level Justification
| Risk | Level |
|:---- |:----- |
| Are there any modifications to system configuration?                           | 0  |
| Are there any additions or modifications to security settings?                 | 0  |
| Is a new workflow introduced or an existing workflow altered significantly?    | 0  |
| Is user behavior affected as a result of this change?                          | 0  |
| Is service outage required to deploy this change?                              | 0  |
| Are new system inter-dependencies introduced?                                  | 0  |
| Has this type of change been attempted before successfully? (Yes = 0, No = 1)  | 0  |

## Plans
- https://github.com/USDOT-SDC/infrastructure/tree/0.4.0/plans

### Test Results
- Check that the following have deployed correctly
  - Lambda: instance-scheduler
- Using [sample_global_schedule.yaml](terraform\instance-scheduler\lambdas\instance-scheduler\sample_global_schedule.yaml), setup the global schedule parameter store
- Observe that instances are started and stopped by the instance-scheduler

## Code Review Checklist
- [x] **Avoid Hardcoding**  
Any string literal values that are likely to change should not be hardcoded and instead put into a config file or something like the AWS Systems Manager Parameter Store. 
This would obviously include any secrets but would also include things URLs, user names, target services, etc. For example, if posting to an SNS topic, we might consider 
externalizing the topic name to make it configurable. For cases where this seems like overkill, a good compromise is hardcoding a default value. In other words, attempt 
to read from an external configuration (e.g. Parameter Store) but use the default value if not found. This does not require much more code but gives you an option to 
change configuration later if needed.

- [x] **Code Reusability**  
We must avoid copying-and-pasting code in multiple places. If we have utility functions that would be useful they should be put in a common library for reuse. 
For Lambda functions, this may mean creating a Lambda layer for utility code that can be reused across multiple Lambdas. For regular Python code, this might involve 
creating a custom Python library. Even if this is the first time writing a piece of code, if it can be made generic and put into a common library/package, we should 
strongly consider doing this. 

- [x] **Self-Documenting Code**  
Code should include comments for clarity when appropriate but should also be self-documenting to the extent possible. This means using meaningful function and variable 
names to help indicate when the function or variable is being used for. Comments above a function that explain the inputs and outputs are useful but not necessary for 
code that has a good function name and can be understood by a junior developer.

- [x] **Security**  
Are secrets being utilized in the code? If so, are they handled properly and not logged to output or exposed. If necessary, is appropriate authentication in place for the code 
to be invoked? Is input data from non-trusted sources appropriately validated and/or sanitized?  
Check for the following:
  - Passwords
  - Private Tokens/Keys
  - Account Numbers
  - Usernames
  - Email Addresses

## Users to Notify
- None

## Security Review Needed (DOT)
- No

### CODE REVIEW

**Comment by JeffUssing** [comment]
@bfitz717 please peer review before we submit for approval

**Review by bfitz717 — APPROVED** [review]
I see the sample yaml files - it looks like the actuals that will be used/deployed are in the parameter store?

**Comment by JeffUssing** [comment]
@bfitz717 correct, the sample files just provide the data schema that must be followed

**Review by alibrodeur — APPROVED** [review]

**Comment by JeffUssing** [comment]
# Test Results
IAW v0.4.0 [Test Plan](https://github.com/USDOT-SDC/infrastructure/blob/0.4.0/plans/test.md)
- :heavy_check_mark: Check that the following have deployed correctly
  - :heavy_check_mark: Lambda: instance-scheduler
- :heavy_check_mark: Using [sample_global_schedule.yaml](https://github.com/USDOT-SDC/infrastructure/blob/main/plans/terraform%5Cinstance-scheduler%5Clambdas%5Cinstance-scheduler%5Csample_global_schedule.yaml), setup the global schedule parameter store
  1. Set global schedule to:
      ```yaml
      Timezone : US/Eastern
      Tags:
          Role:
              Researcher-Workstation:
                  - Day: daily
                    Time: "23:00"
                    Duration: "00:00"
              Support-Workstation:
                  - Day: daily
                    Time: "23:00"
                    Duration: "00:00"
          Name:
              ECSPWSDC03:
                  - Day: daily
                    Time: "10:30"
                    Duration: "12:00"
              ECSPWART01:
                  - Day: daily
                    Time: "19:15"
                    Duration: "1:00"
              ECSPWART02:
                  - Day: daily
                    Time: "19:15"
                    Duration: "00:00"
              Server01:
                  - Day: daily
                    Time: "06:00"
                    Duration: "14:00"
      ```
- :heavy_check_mark: Observe that instances are started and stopped by the instance-scheduler
  1. From the AWS Console: ran a "test" on `instance-scheduler` Lambda
  3. Observed that ECSPWART01 started and set the stop tag = 2022-09-01T00:22+00:00 as scheduled
  4. Observed that ECSPWART02 stopped as scheduled
  5. From the AWS Console: on ECSPWART01 updated stop tag = 2022-08-31T23:30+00:00
  6. From the AWS Console: ran a "test" on `instance-scheduler` Lambda
  7. Observed that ECSPWART01 stopped as scheduled. Also shown in the logs.

**Comment by JeffUssing** [comment]
[tfplan_prod_v0.4.0.zip](https://github.com/USDOT-SDC/infrastructure/files/9465856/tfplan_prod_v0.4.0.zip)

**Pull request merged**
