### PR TITLE
SDC-5759 RE:[CASE 11044684661] Reading from parameter store times-out

### PR DESCRIPTION
**Pull request by JeffUssing**
## Pull Request Information
| Proposed Release Date  | Repository                                                    | Version/Tag                                                                         | Release Type  | Risk Type  | Expected Downtime  |
|------------------------|---------------------------------------------------------------|-------------------------------------------------------------------------------------|---------------|------------|--------------------|
| 2022-11-04             | [infrastructure](https://github.com/USDOT-SDC/infrastructure) | [0.4.0 vs 0.4.1](https://github.com/USDOT-SDC/infrastructure/compare/0.4.0...0.4.1) | Fast Track    | Low        | None               |

## Release
- https://github.com/USDOT-SDC/infrastructure/releases/tag/0.4.1

## Release Notes
- [Release Notes](https://github.com/USDOT-SDC/infrastructure/blob/0.4.1/RELEASE-NOTES.md)

## Summary
- Add logging for reading global schedule from parameter store

## Work Items
- https://securedatacommons.atlassian.net/browse/SDC-5759

## Cost Impacts
- None

## User Guide Updates
- None

## Process, Procedure and Work Instruction
- [Process: Development](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/1332379871)
  - [Procedure: Infrastructure](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2437218305)
    - [WI: Infrastructure, Infrastructure Deployment](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2501017629)

## Impacted System Components
- Instance Scheduler

## Data Load/Processing Impact
- None

## Release Type/Risk Level classification justification
- Release Type: Fast Track
- Risk Level: Low (0)

### Risk Level Justification
| Risk | Level |
|:---- |:----- |
| Are there any modifications to system configuration?                           | 0  |
| Are there any additions or modifications to security settings?                 | 0  |
| Is a new workflow introduced or an existing workflow altered significantly?    | 0  |
| Is user behavior affected as a result of this change?                          | 0  |
| Is service outage required to deploy this change?                              | 0  |
| Are new system inter-dependencies introduced?                                  | 0  |
| Has this type of change been attempted before successfully? (Yes = 0, No = 1)  | 0  |

## Plans
- https://github.com/USDOT-SDC/infrastructure/tree/0.4.1/plans

### Test Results
- Check logs for /aws/lambda/instance-scheduler to ensure it is logging `get_parameter('Global-Schedule')...`

## Code Review Checklist
- [x] **Avoid Hardcoding**  
Any string literal values that are likely to change should not be hardcoded and instead put into a config file or something like the AWS Systems Manager Parameter Store. 
This would obviously include any secrets but would also include things URLs, user names, target services, etc. For example, if posting to an SNS topic, we might consider 
externalizing the topic name to make it configurable. For cases where this seems like overkill, a good compromise is hardcoding a default value. In other words, attempt 
to read from an external configuration (e.g. Parameter Store) but use the default value if not found. This does not require much more code but gives you an option to 
change configuration later if needed.

- [x] **Cyclomatic Complexity**  
Avoid writing functions that have too many nested decision points (conditional logic, looping, etc.). Generally, if a function has more than about 10 decision points 
(adding a point for each if/else/for/while, etc.) it should be broken up into multiple functions.  

- [x] **Code Reusability**  
We must avoid copying-and-pasting code in multiple places. If we have utility functions that would be useful they should be put in a common library for reuse. 
For Lambda functions, this may mean creating a Lambda layer for utility code that can be reused across multiple Lambdas. For regular Python code, this might involve 
creating a custom Python library. Even if this is the first time writing a piece of code, if it can be made generic and put into a common library/package, we should 
strongly consider doing this. 

- [x] **Self-Documenting Code**  
Code should include comments for clarity when appropriate but should also be self-documenting to the extent possible. This means using meaningful function and variable 
names to help indicate when the function or variable is being used for. Comments above a function that explain the inputs and outputs are useful but not necessary for 
code that has a good function name and can be understood by a junior developer.

- [x] **Security**  
Are secrets being utilized in the code? If so, are they handled properly and not logged to output or exposed. If necessary, is appropriate authentication in place for the code 
to be invoked? Is input data from non-trusted sources appropriately validated and/or sanitized?  
Check for the following:
  - Passwords
  - Private Tokens/Keys
  - Account Numbers
  - Usernames
  - Email Addresses

## Users to Notify
- None
- 
## Security Impact Analysis (SIA)
- No

## Meets Definition of Ready?
- Yes

### CODE REVIEW

**Comment by JeffUssing** [comment]
@alibrodeur , @azubrow and @wchupp 

This is a minor update. It adds some logging when reading the global schedule from the parameter store. As well as selecting the correct subnets after we added subnets for the firewall. 

Please review/approve. 

-Jeff

**Review by wchupp — APPROVED** [review]
This is approved, thanks!

**Comment by JeffUssing** [comment]
[tfplan_prod_v0.4.zip](https://github.com/USDOT-SDC/infrastructure/files/9942094/tfplan_prod_v0.4.zip)

**Comment by JeffUssing** [comment]
### Test results
Lines 38-40 of the lambda function, taken from the AWS Console (this matches up w/the repo code)
```python
    print("get_parameter('Global-Schedule')...")
    ssm_parameter = ssm.get_parameter(Name="/Instance-Scheduler/Global-Schedule", WithDecryption=False)
    print("get_parameter('Global-Schedule')...Done")
```
Also checked VPC config, all the subnets are correct

**Pull request merged**
