### PR TITLE
SDC-6108 SDC-6138: Update instance scheduler to read global schedule from S3

### PR DESCRIPTION
**Pull request by JeffUssing**
## Pull Request Information
| Proposed Release Date  | Repository | Version/Tag | Release Type | Risk Type | Expected Downtime |
|---------------------------|-------------|--------------|----------------|------------|-----------------------|
| 2023-05-22 | [infrastructure](https://github.com/USDOT-SDC/infrastructure) | [0.4.3 vs 0.4.4](https://github.com/USDOT-SDC/infrastructure/compare/0.4.3...0.4.4) | Fast Track | Low | None |

## Release
- https://github.com/USDOT-SDC/infrastructure/releases/tag/0.4.4

## Release Notes
- [Release Notes](https://github.com/USDOT-SDC/infrastructure/blob/0.4.4/RELEASE-NOTES.md)

## Summary
- Update instance scheduler to read global schedule from S3, not parameter store

## Work Items
- https://securedatacommons.atlassian.net/browse/SDC-6108
  - https://securedatacommons.atlassian.net/browse/SDC-6138

## Release Notifications
- None

## Cost Impacts
- None

## User Guide Updates
- None

## Process, Procedure and Work Instruction
- [Process: Development](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/1332379871)
  - [Procedure: Infrastructure](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2437218305)
    - [WI: Infrastructure, Infrastructure Deployment](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2501017629)

## Impacted System Components
- instance scheduler

## Data Load/Processing Impact
- None

## Release Type/Risk Level classification justification
- Release Type: Fast Track
- Risk Level: Low (0)

### Risk Level Justification
| Risk                                                                                                                      | Level |
|:------------------------------------------------------------------------------------- |:------ |
| Are there any modifications to system configuration?                                        | 0  |
| Are there any additions or modifications to security settings?                            | 0  |
| Is a new workflow introduced or an existing workflow altered significantly?       | 0  |
| Is user behavior affected as a result of this change?                                            | 0  |
| Is service outage required to deploy this change?                                                | 0  |
| Are new system inter-dependencies introduced?                                                 | 0  |
| Has this type of change been attempted before successfully? (Yes = 0, No = 1)  | 0  |

## Plans
- https://github.com/USDOT-SDC/infrastructure/tree/0.4.4/plans

### Test Results
- [ ] Check that the instance scheduler is reading the global schedule from S3

## Code Review Checklist
- [x] **Avoid Hardcoding**  
Any string literal values that are likely to change should not be hardcoded and instead put into a config file or something like the AWS Systems Manager Parameter Store. 
This would obviously include any secrets but would also include things URLs, user names, target services, etc. For example, if posting to an SNS topic, we might consider 
externalizing the topic name to make it configurable. For cases where this seems like overkill, a good compromise is hardcoding a default value. In other words, attempt 
to read from an external configuration (e.g. Parameter Store) but use the default value if not found. This does not require much more code but gives you an option to 
change configuration later if needed.

- [x] **Cyclomatic Complexity**  
Avoid writing functions that have too many nested decision points (conditional logic, looping, etc.). Generally, if a function has more than about 10 decision points 
(adding a point for each if/else/for/while, etc.) it should be broken up into multiple functions.  

- [x] **Code Reusability**  
We must avoid copying-and-pasting code in multiple places. If we have utility functions that would be useful they should be put in a common library for reuse. 
For Lambda functions, this may mean creating a Lambda layer for utility code that can be reused across multiple Lambdas. For regular Python code, this might involve 
creating a custom Python library. Even if this is the first time writing a piece of code, if it can be made generic and put into a common library/package, we should 
strongly consider doing this. 

- [x] **Self-Documenting Code**  
Code should include comments for clarity when appropriate but should also be self-documenting to the extent possible. This means using meaningful function and variable 
names to help indicate when the function or variable is being used for. Comments above a function that explain the inputs and outputs are useful but not necessary for 
code that has a good function name and can be understood by a junior developer.

- [x] **Security**  
Are secrets being utilized in the code? If so, are they handled properly and not logged to output or exposed. If necessary, is appropriate authentication in place for the code 
to be invoked? Is input data from non-trusted sources appropriately validated and/or sanitized?  
Check for the following:
  - Passwords
  - Private Tokens/Keys
  - Account Numbers
  - Usernames
  - Email Addresses

## Users to Notify
- SDC Support Team

## Security Impact Analysis (SIA)
- No

## Meets Definition of Ready?
- Yes

### CODE REVIEW

**Comment by JeffUssing** [comment]
### dev test results
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                    message                                                                                    |
|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1684550485406 | INIT_START Runtime Version: python:3.9.v19 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:e73d5f60c4282fb09ce24a6d3fe8997789616f3a53b903f4ed7c9132a58045f6            |
| 1684550485756 | current_utc_datetime: 2023-05-20 02:41:25.756883+00:00                                                                                                                        |
| 1684550485758 | START RequestId: 689bb062-bee0-480a-8692-4ea3b450e2b6 Version: $LATEST                                                                                                        |
| 1684550485760 | Getting global schedule...                                                                                                                                                    |
| 1684550489714 | Global Schedule for: Tag:Role Value:Researcher-Workstation                                                                                                                    |
| 1684550490673 | Workstation:ECSDWART02 i-0e4102bcee6179f1e                                                                                                                                    |
| 1684550490673 | Workstation:ECSDWART01 i-0daca5caa7c550bab                                                                                                                                    |
| 1684550490673 | Global Schedule for: Tag:Role Value:Support-Workstation                                                                                                                       |
| 1684550491432 | Workstation:OSTAWSLAS001VG.ad.dot.gov i-051b00546357a42db                                                                                                                     |
| 1684550491432 | Workstation:ECSDWSDC02 i-0be7010e52d5d0ed9                                                                                                                                    |
| 1684550491432 | Workstation:ECSDWSDC03 i-02dffcc11674cf1fd                                                                                                                                    |
| 1684550491432 | Workstation:ECSDWSDC01 i-0ea40269f4a0e68e0                                                                                                                                    |
| 1684550491432 | Workstation:ECSDWSDC04 i-0463fe58e907bbb37                                                                                                                                    |
| 1684550491432 | Global Schedule for: Tag:Name Value:ECSDWSDC03                                                                                                                                |
| 1684550491664 | Workstation:ECSDWSDC03 i-02dffcc11674cf1fd                                                                                                                                    |
| 1684550491664 | Global Schedule for: Tag:Name Value:ECSDWART01                                                                                                                                |
| 1684550492020 | Workstation:ECSDWART01 i-0daca5caa7c550bab                                                                                                                                    |
| 1684550492020 | Global Schedule for: Tag:Name Value:ECSDWART02                                                                                                                                |
| 1684550492391 | Workstation:ECSDWART02 i-0e4102bcee6179f1e                                                                                                                                    |
| 1684550492414 | Getting global schedule...Done                                                                                                                                                |
| 1684550492414 | Getting team schedules...                                                                                                                                                     |
| 1684550543734 | Getting team schedules...                                                                                                                                                     |
| 1684550543734 | Processing schedules with a duration...                                                                                                                                       |
| 1684550543995 | Processing schedules with a duration...Done                                                                                                                                   |
| 1684550543995 | Getting refreshed global schedule...                                                                                                                                          |
| 1684550544773 | Global Schedule for: Tag:Role Value:Researcher-Workstation                                                                                                                    |
| 1684550545488 | Workstation:ECSDWART02 i-0e4102bcee6179f1e                                                                                                                                    |
| 1684550545488 | Workstation:ECSDWART01 i-0daca5caa7c550bab                                                                                                                                    |
| 1684550545488 | Global Schedule for: Tag:Role Value:Support-Workstation                                                                                                                       |
| 1684550546133 | Workstation:OSTAWSLAS001VG.ad.dot.gov i-051b00546357a42db                                                                                                                     |
| 1684550546133 | Workstation:ECSDWSDC02 i-0be7010e52d5d0ed9                                                                                                                                    |
| 1684550546133 | Workstation:ECSDWSDC03 i-02dffcc11674cf1fd                                                                                                                                    |
| 1684550546133 | Workstation:ECSDWSDC01 i-0ea40269f4a0e68e0                                                                                                                                    |
| 1684550546133 | Workstation:ECSDWSDC04 i-0463fe58e907bbb37                                                                                                                                    |
| 1684550546133 | Global Schedule for: Tag:Name Value:ECSDWSDC03                                                                                                                                |
| 1684550546288 | Workstation:ECSDWSDC03 i-02dffcc11674cf1fd                                                                                                                                    |
| 1684550546288 | Global Schedule for: Tag:Name Value:ECSDWART01                                                                                                                                |
| 1684550546473 | Workstation:ECSDWART01 i-0daca5caa7c550bab                                                                                                                                    |
| 1684550546473 | Global Schedule for: Tag:Name Value:ECSDWART02                                                                                                                                |
| 1684550546634 | Workstation:ECSDWART02 i-0e4102bcee6179f1e                                                                                                                                    |
| 1684550546693 | Getting refreshed global schedule...Done                                                                                                                                      |
| 1684550546693 | Processing refreshed schedules without a duration or active schedule...                                                                                                       |
| 1684550546694 | Processing refreshed schedules without a duration or active schedule...Done                                                                                                   |
| 1684550546694 | Process instances with a InstanceScheduler:StopDatetime tag that are due to be stopped...                                                                                     |
| 1684550547456 | Process instances with a InstanceScheduler:StopDatetime tag that are due to be stopped...Done                                                                                 |
| 1684550547495 | END RequestId: 689bb062-bee0-480a-8692-4ea3b450e2b6                                                                                                                           |
| 1684550547495 | REPORT RequestId: 689bb062-bee0-480a-8692-4ea3b450e2b6 Duration: 61734.41 ms Billed Duration: 61735 ms Memory Size: 128 MB Max Memory Used: 103 MB Init Duration: 350.69 ms   |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Review by hghani — APPROVED** [review]

**Comment by JeffUssing** [comment]
@alibrodeur 
I jumped the gun on merging this PR. Could you please comment w/your approval.

**Comment by alibrodeur** [comment]
This is approved.

**Comment by JeffUssing** [comment]
## Test results

```
Test Event Name
null

Response
null

Function Logs
station:ECSPWSDC06 i-058347450fa1d2d53
Workstation:ECSPWSDC07 i-035e91276d97ea2c6
Workstation:ECSPLSDC02 i-0a86bae78d6424853
Global Schedule for: Tag:Name Value:hass-coe-ingest
Workstation:hass-coe-ingest i-055f06e0d6b7dfcba
Global Schedule for: Tag:Name Value:Server01
Workstation:Server01 i-0f7dc4c2394e34953
Global Schedule for: Tag:Name Value:ECSPWSDC03
Workstation:ECSPWSDC03 i-0aa2ef2fae3fff261
Global Schedule for: Tag:Name Value:ECSPWART01
Workstation:ECSPWART01 i-0c891df22ed976fe1
Global Schedule for: Tag:Name Value:ECSPWART02
Workstation:ECSPWART02 i-0f9a56646513b8a9d
Getting global schedule...Done
Getting team schedules...
Team Schedule for: Bucket:prod.sdc.dot.gov.team.acme-research-team Object:Workstation-Schedules/Jeff's Schedule.yaml
Workstation:ECSPWART01 i-0c891df22ed976fe1
Getting team schedules...
Processing schedules with a duration...
Processing schedules with a duration...Done
Getting refreshed global schedule...
Global Schedule for: Tag:Role Value:Researcher-Workstation
Workstation:ECSPWWVT10 i-07ed0cfe35b04d1b7
Workstation:ECSPWSDI10 i-0c2e03c03dbcf7b7d
Workstation:ECSPWSLG02 i-06d1f733413e72834
Workstation:ECSPWWVT02 i-09d6ba8a3ffe77b0d
Workstation:ECSPWFRA03 i-0cdd0720ef7b34da3
Workstation:ECSPWFRA04 i-0738dd18ee3ed690b
Workstation:ECSPWFRA05 i-03e2193d43fdfc699
Workstation:ECSPWHSS02 i-03424a32754376329
Workstation:ECSPWHSS03 i-0e98be1f57ed8ae71
Workstation:ECSPWHSS01 i-011c306063accaa43
Workstation:ECSPWHSIS01 i-0ef2aa4efcdc37cb6
Workstation:ECSPWART02 i-0f9a56646513b8a9d
Workstation:ECSPWART01 i-0c891df22ed976fe1
Workstation:ECSPWWVT25 i-0259f3a61f30adc68
Workstation:ECSPWWVT24 i-03c8c7ef99446e276
Workstation:ECSPWWVT26 i-0ae4f65bfb78dc4a1
Workstation:ECSPWHSIS08 i-0c6006b5a620f28a7
Workstation:ECSPWHSIS05 i-02d403c73560bdb0f
Workstation:ECSPWHSIS04 i-0c0974eb4f6e4bbda
Workstation:ECSPWHSIS03 i-0561887692d4af848
Workstation:ECSPWHSIS06 i-06ae8e1795b4cdb53
Workstation:ECSPWHSIS07 i-08bbda83fb79c01ce
Workstation:ECSPWHSIS02 i-07691838e281dd2cc
Workstation:ECSPWSDI12 i-08e946080c1390d73
Workstation:ECSPWROADII01 i-019100860b43163c2
Workstation:ECSPWHSIS-CLT00 i-0bc299db18cf49a8f
Workstation:ECSPWHSIS-CA00 i-0149739f9c1bbe946
Workstation:ECSPWHSIS-IL00 i-0af71b4d0d8bc2ea3
Workstation:ECSPLFG01 i-050c03c15e91a979a
Workstation:ECSPLFG02 i-04fc8c7c7d1f8b8c3
Workstation:ECSPLFG03 i-07d7668d1b9ca7b66
Workstation:ECSPLFG04 i-0b3c5e84d0a35c70c
Workstation:ECSPWHSS04 i-0d5ee52a69dfb9c69
Workstation:ECSPWROADII02 i-048786d04055c68c5
Workstation:ECSPWROADII04 i-0c39223dd7200d29e
Workstation:ECSPWROADII03 i-04380e264e4feabbe
Global Schedule for: Tag:Role Value:Support-Workstation
Workstation:ECSPLSDC01 i-0f734136fc3b56fc8
Workstation:ECSPWSDC08 i-02b4a068bf159d3c6
Workstation:ECSPWSDC01 i-0cb69169b64fb1843
Workstation:ECSPWSDC02 i-029550cf92e933e48
Workstation:ECSPWSDC03 i-0aa2ef2fae3fff261
Workstation:ECSPWSDC04 i-09d8414a6d3490210
Workstation:ECSPWSDC05 i-0213dd51f0c45853b
Workstation:ECSPWSDC06 i-058347450fa1d2d53
Workstation:ECSPWSDC07 i-035e91276d97ea2c6
Workstation:ECSPLSDC02 i-0a86bae78d6424853
Global Schedule for: Tag:Name Value:hass-coe-ingest
Workstation:hass-coe-ingest i-055f06e0d6b7dfcba
Global Schedule for: Tag:Name Value:Server01
Workstation:Server01 i-0f7dc4c2394e34953
Global Schedule for: Tag:Name Value:ECSPWSDC03
Workstation:ECSPWSDC03 i-0aa2ef2fae3fff261
Global Schedule for: Tag:Name Value:ECSPWART01
Workstation:ECSPWART01 i-0c891df22ed976fe1
Global Schedule for: Tag:Name Value:ECSPWART02
Workstation:ECSPWART02 i-0f9a56646513b8a9d
Getting refreshed global schedule...Done
Processing refreshed schedules without a duration or active schedule...
Processing refreshed schedules without a duration or active schedule...Done
Process instances with a InstanceScheduler:StopDatetime tag that are due to be stopped...
Process instances with a InstanceScheduler:StopDatetime tag that are due to be stopped...Done
END RequestId: e0aab1c3-c420-4969-bf79-99fb64949c18
REPORT RequestId: e0aab1c3-c420-4969-bf79-99fb64949c18	Duration: 63709.94 ms	Billed Duration: 63710 ms	Memory Size: 128 MB	Max Memory Used: 108 MB

Request ID
e0aab1c3-c420-4969-bf79-99fb64949c18
```

**Pull request merged**
