### PR TITLE
SDC-5435 SDC-4868: Update Python Runtime, Add pre-commit hook, Misc. Housekeeping

### PR DESCRIPTION
**Pull request by JeffUssing**
# Infrastructure Pull Request

|                              |            |
|------------------------------|------------|
| __Proposed Release Version__ | 0.4.5      |
| __Proposed Release Date__    | 2024-02-16 |
| __Release Type__             | Fast Track |
| __Risk Type__                | Low        |
| __Expected Downtime__        | None       |

## Summary

- Update Python to 3.11
- Add S3 VPC Endpoint
- Update PR template
- Add pre-commit hook
- Update std document formats

## Work Items

- Parent: [SDC-5435: Implement Backup & Disaster Recovery 2](https://securedatacommons.atlassian.net/browse/SDC-5435)
  - Child: [SDC-4868: Verify Implementation of Backup & DR for Ephemeral Resources](https://securedatacommons.atlassian.net/browse/SDC-4868)

## Users to Notify

- None

## Release Notifications
- None

## Cost Impacts

- None

## User Guide Updates

- None

## Process, Procedure and Work Instruction
- [Process: Development](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/1332379871)
  - [Procedure: Infrastructure](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2437218305)
    - [WI: Infrastructure, Infrastructure Deployment](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2501017629)

## Impacted System Components

- None

## Data Load/Processing Impact

- None

## Release Type Classification and Justification

- Release Type: Fast Track

## Risk Level Classification and Justification

- Risk Level: Low (0)

### Risk Level Justification
| Risk                                                                           | Level |
|:------------------------------------------------------------------------------ |:-----:|
| Are there any modifications to system configuration?                           |   0   |
| Are there any additions or modifications to security settings?                 |   0   |
| Is a new workflow introduced or an existing workflow altered significantly?    |   0   |
| Is user behavior affected as a result of this change?                          |   0   |
| Is service outage required to deploy this change?                              |   0   |
| Are new system inter-dependencies introduced?                                  |   0   |
| Has this type of change been attempted before successfully? (Yes = 0, No = 1)  |   0   |

## Plans

- https://github.com/USDOT-SDC/infrastructure/tree/0.4.5/plans

## DevOps Checklist
- [x] **Pull Request Title**  
The pull request title should be in accordance with the following naming convention:  
_SDC-{parent} SDC-{child} CRB-{000}: {CRB Title}_  
For example:
  - SDC-5332 SDC-3798 CRB-526: Web Portal: Fix Overwrite Export Request Issue
  - SDC-5435 SDC-4870 CRB-515: Waze: Implement point-in-time recovery for DynamoDB
  - SDC-6548 SDC-6480 CRB-522: Web Portal: Edit Footer to get rid of contract number

- [x] **Avoid Hardcoding**  
Any string literal values that are likely to change should not be hardcoded and instead put into a config file or something like the AWS Systems Manager Parameter Store.

- [x] **Self-Documenting Code**  
Code should include comments for clarity, but should also be self-documenting. This means using meaningful function and variable names to help indicate why/when the function or variable is used.

- [x] **Docstrings and Type Hints**  
In Python scripts:
  - Include docstrings: [Wikipedia: Docstring ∬Python](https://en.wikipedia.org/wiki/Docstring#Python)
    ```python
    def my_function(arg1, arg2):
    """This function does something.

    Args:
      arg1: The first argument.
      arg2: The second argument.

    Returns:
      The result of doing something.
    """
    # Do something with arg1 and arg2.
    return result
    ```
  - Use type hints: [Python Support for Type Hints](https://docs.python.org/3/library/typing.html)

- [x] **Logging and Debugging**  
Code should have an appropriate amount of logging to be able to troubleshoot foreseeable problems.

- [x] **Error Handling**  
Exceptions should be logged unless they are an expected, valid use case. Exceptions should NOT be swallowed unless they are recoverable.

- [x] **Security**  
Are secrets being utilized in the code? If so, are they handled properly and not logged to output or exposed. Does this change require a Security Impact Analysis (SIA)?  
Check for the following:
  - Passwords
  - Private Tokens/Keys
  - Account Numbers
  - Usernames
  - Email Addresses

## Security Impact Analysis (SIA)
  
  
  - [x] I have reviewed the [Performing a Security Impact Analysis (SIA)](https://securedatacommons.atlassian.net/wiki/spaces/DO/pages/2642935856) work instructions.
  
  - This change __DOES NOT__ require a SIA

## Meets Definition of Ready?
- [x] Yes

### CODE REVIEW

**Review by williamrsharp — DISMISSED** [review]

**Comment by JeffUssing** [comment]
Thanks @williamrsharp 

@ShylaMorisetty
This PR is a little different than other repos. It functions as both the PR and the CRB. I'm happy to meet and review it with you, if you like. Otherwise, could you please review and comment with approval.

**Review by ShylaMorisetty — DISMISSED** [review]
Approved

**Comment by JeffUssing** [comment]
### Check the S3 VPC Endpoint
- all endpoints created, policies in place and correct

image

**Comment by ShylaMorisetty** [comment]
Why am I on this email chain? What is this?

Jared

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
